# Generated by Django 5.2.4 on 2025-07-13 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_alter_perfil_background'),
        ('juegos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biblioteca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='biblioteca', to='accounts.user')),
            ],
        ),
        migrations.CreateModel(
            name='JuegoBiblioteca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_adquisicion', models.DateTimeField(auto_now_add=True)),
                ('horas_jugadas', models.PositiveIntegerField(default=0)),
                ('ultima_vez_jugado', models.DateTimeField(blank=True, null=True)),
                ('biblioteca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.biblioteca')),
                ('juego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='juegos.juego')),
            ],
        ),
        migrations.AddField(
            model_name='biblioteca',
            name='juegos',
            field=models.ManyToManyField(related_name='bibliotecas', through='biblioteca.JuegoBiblioteca', to='juegos.juego'),
        ),
    ]
