# Generated by Django 5.2.4 on 2025-07-14 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
        ('juegos', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='juegobiblioteca',
            constraint=models.UniqueConstraint(fields=('biblioteca', 'juego'), name='unique_juego_por_biblioteca'),
        ),
    ]
