# Generated by Django 5.2.4 on 2025-07-06 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=400)),
                ('rol', models.CharField(choices=[('user', 'Usuario'), ('admin', 'Administrador'), ('mod', 'Moderador'), ('dev', 'Creador de Juegos')], default='user', max_length=10)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('suspendido', 'Suspendido'), ('baneado', 'Baneado')], default='activo', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_perfil', models.CharField(default='Nuevo Usuario', max_length=50)),
                ('edad', models.PositiveIntegerField(blank=True, null=True)),
                ('sexo', models.CharField(blank=True, max_length=10, null=True)),
                ('descripcion', models.TextField(default='Esta es su Descripción', null=True)),
                ('avatar', models.URLField(default='https://i.pinimg.com/236x/d4/74/1c/d4741cb779ddec6509ca1ae0cb137a7d.jpg')),
                ('background', models.URLField(default='htps://w.wallhaven.cc/full/n6/wallhaven-n68mj6.jpg')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to='accounts.user')),
            ],
        ),
    ]
