# Generated by Django 5.2.4 on 2025-07-06 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='background',
            field=models.URLField(default='https://w.wallhaven.cc/full/ml/wallhaven-mldl19.jpg'),
        ),
    ]
