# Generated by Django 5.2.4 on 2025-07-13 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('imagen', models.URLField(default='https://placeholder.com/juego.jpg')),
                ('fecha_lanzamiento', models.DateField(blank=True, null=True)),
                ('desarrollador', models.CharField(max_length=100)),
            ],
        ),
    ]
